### PR TITLE
check equality for recordlists

### PR DESCRIPTION
**Pull request by lepistone**

### CODE REVIEW

**Comment by gurneyalex** [comment]
:+1:

**Comment by mistotebe** [comment]
Have just been investigating what would be required to have records/recordlists be hashable (for use in sets) and I am not sure they should compare equal when out of order/containing duplicates. Or maybe having a RecordSet subclass that is equal regardless of order/duplicates?

What do you think? Also what about False, that can still appear in a recordlist after going through it.

**Comment by mistotebe** [comment]
after that we can have:
```python
def __hash__(self):
    return hash((self.__class__, self._model, self.id))
```

**Comment by florentx** [comment]
Thank you @lepistone for this proposal.

I concur with @mistotebe  that we should only compare equal if `.id` are equal.

**Comment by florentx** [comment]
I've merged the first commit only: the RecordLists are equals if they have the same order.

**Pull request closed without merging**
