### PR TITLE
Fix v10 support

### PR DESCRIPTION
**Pull request by yucer**
- support new Odoo namespaces and Registry used in v10

- the changes should be backward compatible

### CODE REVIEW

**Comment by katyukha** [comment]
Import block in this PR does not cover all the cases.

Here is import block which cover most of cases:
```python
    try:
        # Odoo 10.0+

        # this is required if there are addons installed via setuptools_odoo
        pkg_resources.declare_namespace('odoo.addons')

        # import odoo itself
        import odoo
        import odoo.release  # to avoid 9.0 with odoo.py on path
    except (ImportError, KeyError):
        # KeyError is raised when no namespace 'odoo.addons' declared
        # (odoo 9.0 install for example)
        try:
            # Odoo 9.0 and less versions
            import openerp as odoo
        except ImportError:
            raise
```

**Comment by yucer** [comment]
I like your proposal. What should I do then ?

**Comment by katyukha** [comment]
Here is [code](https://github.com/katyukha/odoo-helper-scripts/blob/dev/lib/pylib/lodoo.py) that I use to monkey-patch *erppeek* to work with odoo 10.0.
It simply replaces erppeek's function *start_start_odoo_services*

**Comment by matrixise** [comment]
Is there a test where you test with an older version of Odoo and a new one, because we would like to keep the compatibility.

**Comment by florentx** [comment]
Thank you for your patch.
I've pushed a bunch of changes in master branch for Odoo v10 support.

**Pull request closed without merging**
